/*!
 *  Stunnplate script.js
 *  Version: 1.3.2
 *
 */
 /* 
 *  
 *  Notes:
 *  Main JS file to include entire library followed by custom scripts.
 *
 * 
 */

/*-------------------------------------------------------*/
/*-     IMPORT LIBRARY                                  -*/
/*-------------------------------------------------------*/

/* stunn_import replaces old @import style so that concat is not required for dev */

/*- Core -*/
stunn_import('lib/core/safeConsole.js');
//stunn_import('lib/jsonForm.0.6.5/script.js');
stunn_import('lib/touchListener/touchListener.js');

/*- Modules -*/
//stunn_import('lib/simple-fixed-header/simple-fixed-header.js'); //Less fancy than Matt's
stunn_import('lib/fixedHeader/fixedheader.js'); //Fancier than all before it!!!
stunn_import('lib/layout/layout.js');
stunn_import('lib/tabbed/tabbed.js');
stunn_import('lib/modal/modal.js');
stunn_import('lib/nav/nav.js');
stunn_import('lib/carousel/carousel.js');
//stunn_import('lib/almostInView/almostInView.js'); //BUGGY
stunn_import('lib/back-to-top/back-to-top.js');
stunn_import('lib/maps/maps.js');

stunn_import('lib/flexSlider/flexSlider.js');

stunn_import('lib/googleFileTrack/jquery.googleFileTrack.js');

/*- Vendor -*/
/* JQuery and Modernizr included on page for load via CDN as this is usually cached (Modernizr must be loaded in head for HTML5 Shiv to work) */
stunn_import('lib/vendor/elementQuery.min.js');

/*
 * STUNN IMPORT
 * ------------
 * Loads a script by js for when this page is included on the page rather than the concatinated version generated by Sublime's concat.py - which now looks for "stunn_import('../path/to/some/script.js');" and replaces it with the file contents but during dev we may just access the non-concatinated version
 *
 */
function stunn_import(filePath){   
    var failAfter = 3000,
        success = function(){clearTimeout(t);},
        // remember to comment out this alert on go live
        error = function(){alert("Unable to load "+ script.src);},
        t = setTimeout(error,failAfter);    
    
    var script = document.createElement('script');
        script.src = filePath;
        //script.type = 'text/javascript';
        script.onreadystatechange = success;
        script.onload = success;
    
    var head = document.getElementsByTagName('head')[0];
        head.appendChild(script);

}

/*-------------------------------------------------------*/
/*- SITE SPECIFIC SCRIPT                                -*/
/*-------------------------------------------------------*/

// Add awesome here!!!

// $(function(){
//     $('body > section').almostInView();
// })




